resources:                          # To pull the shared templates to be available for current pipeline.
  repositories:
  - repository: Shared_Templates
    type: github
    endpoint: karty333
    name: karty333/Shared_Templates
pool:
  vmImage: ubuntu-latest               #image name(if Microsoft-hosted) or agent pool name (if self-hosted)
stages:
 - stage: Checkout
   jobs: 
    - job: Checkout_Templates_and_Code
      steps:
       - checkout: self                # Checkout the current project repo
       - checkout: Shared_Templates    # Checkout the Shared_Templates
 - template: maven_template.yml@Shared_Templates  # appropriate templates will be called in sequence according to the project requirements.
 - template: artifactory_upload.yml@Shared_Templates
 
