trigger: none
parameters:                          # Provide artifact version to be deployed as input parameter for 'Artifact_Version' variable 
- name: Artifact_Version             # while triggering release pipeline.
  displayName: Artifact version for Deployment
  default: 'latest'
resources:
  repositories:
  - repository: Shared_Templates     # To pull the shared templates to be available for current pipeline.
    type: github
    endpoint: karty333
    name: karty333/Shared_Templates
pool:
  vmImage: ubuntu-latest             #image name(if Microsoft-hosted) or agent pool name (if self-hosted)
stages:
 - stage: Checkout
   jobs: 
    - job: Checkout_Templates_and_Code
      steps:
       - checkout: self              # Checkout the current project repo
       - checkout: Shared_Templates  # Checkout the Shared_Templates
 - template: artifactory_download.yml@Shared_Templates  # appropriate templates will be called in sequence according to the project 
   parameters:                                         # requirements.
     Artifact_Version: ${{ parameters.Artifact_version }}
 - template: jboss_test.yml@Shared_Templates
   parameters:
     stage: 'Dev'
     job: 'jboss_deployment_dev'
     env: 'dev'
 - template: jboss_test.yml@Shared_Templates
   parameters:
     stage: 'QA'
     job: 'jboss_deployment_qa'
     env: 'qa'
 - template: jboss_test.yml@Shared_Templates
   parameters:
     stage: 'PROD'
     job: 'jboss_deployment_prod'
     env: 'PROD'
